
const About = () => (
  <div className="about container">
    <div className="row justify-content-center">
      <div className="col-8">
        <h1 className="common-title">A Glimpse into My Journey</h1>
      </div>
    </div>
    <div className="row justify-content-center">
      <div className="col-md-5">
        <p className="common-paragraph">
          I&apos;m a soon-to-be university graduate with a passion for front-end programming. From the moment I wrote my first line of HTML and CSS, I knew I had found my calling. As I prepare to take my skills to the next level, I&apos;m excited to embark on this journey of creating beautiful, user-friendly web experiences. I thrive on turning creative ideas into functional, visually stunning websites that leave a lasting impression.
          <br/><br/><br/>generated by: ChatGPT
        </p>
      </div>
      <div className="col-md-6">
        <p className="common-paragraph">
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
        </p>
      </div>
    </div>
  </div>
)

export default About